---
- name: test_required_fields
  host: localhost
  requests:
    - name: test_request_name

- name: test_all_fields
  host: localhost
  scheme: https
  timeout: 10
  port: 3000
  requests:
    - name: test_post
      method: !post

    - name: test_post
      method: !post
      resource: /api/test
      hash: hash_location
      headers:
        Accept-Language: en-US,en;q=0.8
        User-Agent: Mozilla/5.0 Firefox/50.0
      params:
        param1: value1
        param2: value2
      body:
        prop1a: val1a
        prop1b:
          prop2a: val2a
          prop2b:
            prop3a: val3a
            prop3b: val3b

    - name: basic_auth_request
      auth: !basic
        username: test_username
        password: test_password

    - name: bearer_auth_request
      auth: !bearer
        token: abcd$1234.231&4dfs-asdfjsdv.vsd
        # - name: jsonplaceholder
        #   host: jsonplaceholder.typicode.com
        #   scheme: https
        #   port: 3001
        #   timeout: 10
        #   requests:
        #     - name: get_posts
        #       resource: /posts/1
        #
        #     - name: get_comments
        #       resource: /comments
        #       params:
        #         postId: 1
        #
        #     - name: create_post
        #       resource: /posts
        #       method: !post
        #       auth: !bearer
        #         token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDAyMDU4MjIsImlzX2FkbWluIjpmYWxzZSwidXNlcl9pZCI6Mn0.1uKA2rzEoOajZ5bBnxes9XIUo2iOwKCD7bVVwvRzJ48
        #       body:
        #         title: foo
        #         body: Lorem ipsum dolar sit amet.
        #         userId: 1
