---
- name: test_minimum_config
  host: jsonplaceholder.typicode.com
  requests:
    - name: test_default_request

- name: test_all_methods
  host: jsonplaceholder.typicode.com
  scheme: https
  timeout: 10
  port: 443
  requests:
    - name: get_resource
      method: !get
      resource: /posts/1

    - name: get_params
      method: !get
      resource: /posts
      params:
        userId: 1

    - name: post_request
      method: !post
      resource: /posts
      body:
        title: Lorem ipsum
        body: Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.
        userId: 1

    - name: put_request
      method: !put
      resource: /posts/1
      body:
        id: 1
        title: Lorem ipsum
        body: Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.
        userId: 1

    - name: patch_request
      method: !patch
      resource: /posts/1
      body:
        title: Dolar sit amet

    - name: delete_request
      method: !delete
      resource: /posts/1
      body:
        foo: for some reason jsonplaceholder returns a 500 if there's no body provided for a DELETE request
